backend:
  name: github
  repo: w17679210701-blip/Omen.github.io
  branch: main

media_folder: "images" # 图片存放路径
public_folder: "/images"

collections:
  - name: "content"
    label: "主页内容"
    files:
      - file: "index.html"
        label: "基础信息"
        name: "info"
        fields:
          - {label: "关于我", name: "about_text", widget: "text"}
          - {label: "当前状态", name: "status_text", widget: "string"}
